version: '3.9'

services:
  gateway:
    build: ./backend/gateway_service
    ports:
      - '8000:8000'
    depends_on:
      - user_service
      # - profile_service
      # - affiliation_service
      # - plan_service
      # - payment_service
      # - medical_history_service
      # - document_service
      # - authorization_service
      
  user_service:
    build: ./backend/user_service
    ports:
      - '8001:8000'
    depends_on:
      - user_db
  
  user_db:
    image: postgres:15
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: userDB
      
  profile_service:
    build: ./backend/profile_service
    ports: 
      - '8002:8000'
    depends_on:
      - profile_db
    
  profile_db:
    image: postgres:15
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: profileDB

  affiliation_service:
    build: ./backend/affiliation_service
    ports: 
      - '8003:8000'
    depends_on:
      - affiliation_db

  affiliation_db:
    image: postgres:15
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: affiliationDB
  
  plan_service:
    build: ./backend/plan_service
    ports:
      - '8004:8000'
    depends_on:
      - plan_db
  
  plan_db:
    image: postgres:15
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: planDB
  
  pyment_service:
    build: ./backend/payment_service
    ports:
      - '8005:8000'
    depends_on:
      - payment_db

  payment_db:
    image: postgres:15
    ports:
      - '5437:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: paymentDB

  medical_history_service:
    build: ./backend/medical_history_service
    ports:
      - '8006:8000'
    depends_on:
      - medical_history_db

  medical_history_db:
    image: postgres:15
    ports: 
      - '5438:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: medical_historyDB

  document_service:
    build: ./backend/document_service
    ports:
      - '8007:8000'
    depends_on:
      - document_db
        
  document_db:
    image: postgres:15
    ports:
      - '5439:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: documentDB

  authorization_service:
    build: ./backend/authorization_service
    ports:
      - '8008:8000'
    depends_on:
      - authorization_db
  
  authorization_db:
    image: postgres:15
    ports:
      - '5440:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: authorizationDB


  frontend:
    build: ./frontend/vite-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/vite-app:/app  # Sincroniza todo el proyecto
      - /app/node_modules         # Evita sobrescribir node_modules
    command: sh -c "npm install && npm run dev"
    depends_on:
      - gateway