version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  auth_service:
    build: ./backend/auth_service  
    ports:
      - "8001:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5434/videocalldb

  user_service:
    build: ./backend/user_service
    ports:
      - "8002:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5435/videocalldb

  appointment_service:
    build: ./backend/appointment_service
    ports:
      - "8003:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5436videocalldb
  
  profile_service:
    build: ./backend/profile_service
    ports: 
      - "8004:8000"
    volumes:
      - ./backend/profile_service/profilepics:/app/profilepics
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5437/videocalldb

  affiliation_service:
    build: ./backend/affiliation_service
    ports:
      - "8005:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://admin:12345@postgres:5438/videocalldb

  gateway:
    build: ./backend/gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - user_service
      - appointment_service
      - profile_service
    environment:
      - SECRET_KEY=supersecreto123

  frontend:
    build: ./frontend/vite-app
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/vite-app:/app  # Sincroniza todo el proyecto
      - /app/node_modules         # Evita sobrescribir node_modules
    command: npm run dev
    depends_on:
      - gateway

volumes:
  postgres_data: