version: '3.9'

services:
  # Backend Django REST API
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - media_volume:/app/media
      - static_volume:/app/staticfiles
    environment:
      - DEBUG=${DEBUG:-False}
      - SECRET_KEY=${SECRET_KEY:-your-production-secret-key-here}
      - DB_NAME=${DB_NAME:-medinext_db}
      - DB_USER=${DB_USER:-admin}
      - DB_PASSWORD=${DB_PASSWORD:-12345}
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  # Base de datos PostgreSQL
  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: ${DB_NAME:-medinext_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  # Frontend React/Vite
  frontend:
    build: 
      context: ./frontend/vite-app
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/vite-app:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8000/api
    depends_on:
      - backend
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"

volumes:
  postgres_data:
  static_volume:
  media_volume: